Feat/events linkasset
kuzzleio/kuzzle-device-manager pull request #136
Opened 2021-11-16 13:39 UTC by rolljee

close #122

2021-11-16 13:45 UTC, rolljee commented
missing new tests for events

2021-11-16 18:57 UTC, Aschen requested changes
I think we should emit 1 event per asset/device pair.

Also you didn't add functional or unit tests to this PR

2021-11-16 18:57 UTC, Aschen commented on lib/core-classes/DeviceService.ts
> +    await global.app.trigger(
Same comment here

2021-11-17 16:36 UTC, rolljee commented
functional tests are coming in the next commit :+1:

2021-11-24 20:16 UTC, Aschen approved these changes

2021-11-25 09:20 UTC, rolljee commented on lib/core-classes/DeviceService.ts
> +      results.successes.push(...successes);
I have a PR that modify this behavior, I am gonna merge this one, and get things done in the orther PR

2021-11-25 10:24 UTC, merged