Permit to push measures directly on asset
kuzzleio/kuzzle-device-manager pull request #189
Opened 2022-05-30 09:31 UTC by ChillPC

# What does this PR do ?

Permit to push measures directly on asset

## How should this be manually tested?

```sh
curl http://127.0.0.1:7512/_/device-manager/eng1/assets/type1-mod1-ref1/measures --json ' { "measures": [ { "type": "temperature", "values": { "temperature": 99.99 } } ] }'
```

## Other changes

Refinement of service and controller roles

2022-05-31 13:34 UTC, ChillPC commented on lib/types/measures/Measure.ts
> +  values: JSONObject;
`MeasureContent` It was specified as `JSONObject` before, so I did not change that

2022-05-31 14:11 UTC, Aschen requested changes

2022-05-31 14:11 UTC, Aschen commented on lib/types/measures/Measure.ts
> +export interface BaseAssetMeasure extends KDocumentContent {
As we discussed:
 - a `MeasureContent` represents the content of the entire measure document as it is stored in the database
 - a `Measurement` represents the actual measure 

And finally, the measure name will always be present, not only for the asset (see https://github.com/kuzzleio/kuzzle-device-manager/issues/168#issuecomment-1142182855)

2022-05-31 14:11 UTC, Aschen commented on lib/utils/measure.ts
> +export function validateBaseMeasure (toValidate: JSONObject): boolean {
Why did you extract this method to use it only once?

2022-05-31 14:31 UTC, ChillPC commented on lib/controllers/AssetController.ts
> +    request.input.args.index = engineId;
Left over from copy paste or something, removed

2022-06-01 07:28 UTC, ChillPC commented on features/AssetController.feature
> +    When I successfully execute the action "device-manager/asset":"postMeasures" with args:
Seems like it should be resolve in #168

2022-06-01 07:29 UTC, ChillPC commented on lib/controllers/AssetController.ts
> +    measureService: MeasureService
Too much work for now

2022-06-01 14:21 UTC, merged