Store reason of discard payload
kuzzleio/kuzzle-device-manager pull request #283
Opened 2023-03-24 16:25 UTC by OlivierCavadenti

- Store if a payload is skipped, valid or error.
- Store the reason of the error, when a user defined validation error occurs.

2023-03-24 19:14 UTC, Aschen requested changes
This feature should be documented here https://github.com/kuzzleio/kuzzle-device-manager/blob/master/doc/2/guides/measures-ingestion/index.md?plain=1#L109

And also add the `state` and `reason` here https://github.com/kuzzleio/kuzzle-device-manager/blob/master/doc/2/guides/measures-ingestion/index.md?plain=1#L232

2023-03-24 19:14 UTC, Aschen commented on lib/modules/decoder/PayloadService.ts
> +    let state: StateDecoder = StateDecoder.VALID;
```suggestion
    let state = StateDecoder.VALID;
```

2023-03-24 19:14 UTC, Aschen commented on lib/modules/decoder/StateDecoder.ts
> +export enum StateDecoder {
Maybe `DecodingState` is a better name otherwise it's confusing with the Decoder class

2023-03-24 19:14 UTC, Aschen commented on lib/modules/decoder/PayloadService.ts
> +        error.message || (error.toJSON ? error.toJSON().message : undefined);
Why using `toJSON` ? If it's an Error or a KuzzleErro then we always have the `message` property

2023-03-24 19:14 UTC, Aschen commented on lib/modules/decoder/SkipError.ts
> +    // needed for match Error constructor signature
You should propagate the message so user may skip message with a reason also

2023-03-28 12:23 UTC, OlivierCavadenti commented
> [ingestion/index.md?plain=1#L109](https://github.com/kuzzleio/kuzzle-device-manager/blob/master/doc/2/guides/measures-ingestion/index.md?plain=1#L109)
> 
> And also add the `state` and `reason` here https://github.com/kuzzleio/kuzzle-device-manager/blob/master/doc/2/guides/measures-ingestion/index.md?plain=1#L232

I still need to do that.
Btw, the state enum is stored in ES with a number, maybe could be better, for queries and clarity, to store the name of the value and not the number (0,1, 2) ? @Aschen

2023-03-28 14:20 UTC, Aschen commented
> Btw, the state enum is stored in ES with a number, maybe could be better, for queries and clarity, to store the name of the value and not the number (0,1, 2) 

Yes it would be better to have string values :+1:

2023-03-28 15:42 UTC, Aschen approved these changes

2023-03-29 07:27 UTC, merged