Kzlprd 323 asset metadata
kuzzleio/kuzzle-device-manager pull request #346
Opened 2024-06-05 08:31 UTC by cyrng

## What does this PR do ?
It will add two fields ('strategy' et 'format') in MetadataProperty to allow geoshape circle and date format according to ES documentation.

https://www.elastic.co/guide/en/elasticsearch/reference/7.17/geo-shape.html#_circle
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/mapping-date-format.html

### Boyscout

Types tests can pass successfully instead of putting typescript ignores.

2024-06-20 14:40 UTC, cyrng commented
PR related to KZL-323-asset-geolocation-metadata from the iot-platform to make it work correctly and to avoid CI failure on the feature

2024-06-21 07:20 UTC, etrousset requested changes
Il manque pas la doc pour de cette API?

2024-06-24 07:49 UTC, alexandrebouthinon approved these changes

2024-06-24 07:49 UTC, alexandrebouthinon commented on doc/2/controllers/assets/replace-metadata/index.md
> +```json
Use the `js` label to better comment coloration (no comment when using `json`)
```suggestion
```js
```

2024-07-01 09:35 UTC, inkedsquid approved these changes

2024-07-04 10:40 UTC, etrousset approved these changes

2024-07-08 08:10 UTC, merged