fix: lastMeasuredAt
kuzzleio/kuzzle-device-manager pull request #387
Opened 2024-12-26 16:08 UTC by thomas-mauran

This was creating a bug where if a payload with an older measure was received we would set lastMeasuredAt to 0

2024-12-27 10:51 UTC, afondard approved these changes

2024-12-30 08:07 UTC, rolljee requested changes
You should add a test for this case :)

2025-01-22 11:00 UTC, rolljee commented
You need to remake this PR.

Start from 2-dev instead of 3-dev

2025-01-22 11:00 UTC, rolljee requested changes
See comment

2025-02-03 09:37 UTC, thomas-mauran commented
Good brannch is #399

2025-02-03 09:37 UTC, closed without merging